variables:
  NIX_PATH: nixpkgs=https://nixos.org/channels/nixos-20.03-small/nixexprs.tar.xz
  NIXOS_CONFIG: $CI_PROJECT_DIR/prod.nix

build:
  image: nixos/nix:2.3.6
  script: nix-build '<nixpkgs/nixos>' -A vm
