variables:
  NIX_PATH: nixpkgs=https://nixos.org/channels/nixos-20.03-small/nixexprs.tar.xz
  NIXOS_CONFIG: $CI_PROJECT_DIR/prod.nix

build:
  image: nixos/nix:2.3.6
  before_script:
    - nix-env -f '<nixpkgs>' -iA cachix bash
    - cachix use xfix-pw
    - nix path-info --all > /tmp/store-path-pre-build
  script:
    - nix-build '<nixpkgs/nixos>' -A vm
  after_script:
    - bash -c "comm -13 <(sort /tmp/store-path-pre-build | grep -v '\.drv$') <(nix path-info --all | grep -v '\.drv$' | sort) | cachix push xfix-pw"
