build:
  image: nixos/nix:2.3
  script: nix-build --no-out-link packages/*.nix
  cache:
    paths:
    - /nix

test:
  image: nixos/nix:2.3
  script: nix-build --no-out-link tests/*.nix
  cache:
    paths:
    - /nix
