name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: 30 3 * * *

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - babelmark
          - pastebinrun
          - sandbox
          - xbot
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-22.05-small
      - uses: cachix/cachix-action@v10
        with:
          name: xfix-pw
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
      - run: nix-build packages/${{ matrix.package }}.nix

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - babelmark
          - pastebinrun
          - sandbox
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-22.05-small
          extra_nix_config: system-features = nixos-test benchmark big-parallel kvm
      - uses: cachix/cachix-action@v10
        with:
          name: xfix-pw
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
      - run: nix-build tests/${{ matrix.test }}.nix

  update-niv-packages:
    name: Update Niv packages
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell -p niv --run 'niv update'
      - uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update niv packages
          title: Update niv packages
          branch: master
