name: CI

on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron: 30 3 * * *

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - babelmark
          - pastebinrun
          - sandbox
          - xbot
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-23.05-small
      - uses: cachix/cachix-action@v12
        with:
          name: xfix-pw
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
      - run: nix-build packages/${{ matrix.package }}.nix

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - babelmark
          - pastebinrun
          - sandbox
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-23.05-small
          extra_nix_config: system-features = nixos-test benchmark big-parallel kvm
      - uses: cachix/cachix-action@v12
        with:
          name: xfix-pw
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
      - run: nix-build tests/${{ matrix.test }}.nix
