name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: 30 3 * * *

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - babelmark
          - pastebinrun
          - sandbox
          - xbot
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-21.11-small
      - uses: cachix/cachix-action@v10
        with:
          name: xfix-pw
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
      - run: nix-build packages/${{ matrix.package }}.nix
