name: Deployment

on:
  push:
    branches:
      - master
      - test-deploy

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: webfactory/ssh-agent@d4b9b8ff72958532804b70bbe600ad43b36d5f2e
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}
      - uses: cachix/install-nix-action@300721fe01bc8c4cf4677859b80e55154023c7d3
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      - run: nix-shell -p colmena --run 'colmena apply'
