# SPDX-FileCopyrightText: 2023 Kamila Borowska <kamila@borowska.pw>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Check formatting

on:
  push:
    branches:
      - renovate/lock-file-maintenance
  pull_request:
    branches:
      - master

jobs:
  alejandra:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@8887e596b4ee1134dae06b98d573bd674693f47c # v26
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - run: nix fmt -- --check .
